stages:
  - build
  - docker-build

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
    - echo "Build Complete!"

# Docker in Docker needs to use the Docker executor
# If you already have an executor running, you can check it in GitLab's admin panel
# For the exact env variables, you can look at GitLab's documentation
docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # We add double quotes in case the creds contain spaces
    # We add gitlab.tylerchen.ca instead of $CI_REGISTRY because gitlab.tylerchen.ca uses a proxy
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.tylerchen.ca
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # --pull flag ensures to fetch changes before building.
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Registry image:" $CI_REGISTRY_IMAGE
