stages:
  - clean
  - deploy

# Stops or removes previous containers that allows deploy to run.
# Some commands can fail if the container does not exist
clean:
  stage: clean
  image: docker:latest
  allow_failure: true
  script:
    - docker images -qf "dangling=true" # Removes *dangling* images aka. the ones that are "none" with tag "none"
    - docker stop personal-website

# Builds a docker image that is connected to the docker socket where the runner is located.
# Runs the container with:
#   --rm : cleans up after container stops
#   -d : detached
#   -p : ports
#   --name : name of the container
#   $CI_REGISTRY_IMAGE: environment variable set by GitLab Runner
#   5000 on host, 3000 inside the container
deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker run -d -p 5000:3000 --rm --restart --name personal-website $CI_REGISTRY_IMAGE:latest
